print("||| NAT HWAG UNOFFICIAL BIRTHDAY SONG GENERATOR FOR ROOKIES |||")
print(" ")
print("Happy birthday to you")
print("Happy birthday to you")
print("Happy birthday dear, Arty Kimmy")
print("Happy birthday to yoooooooooooooooooooooooou!!!")