print("======================================================")
print(" ")
print("===== NAT HWAG UNOFFICIAL RESTRAUNT FOR BAD FOOD =====")
print(" ")
print("======================================================")
print(" ")
