print("||| NAT HWAG UNOFFICIAL GROCERY STORE FOR STEALING MONEY |||")
print(" ")
print("====================================================")
print(" ")
x = int(input("HOW MANY ITEMS ARE YOU PURCHASING? "))
total = 0
print(" ")
for i in range (0,x):
    print("====================================================")
    print(" ")
    name = (input("WHAT ITEM DO YOU WANT TO PURCHASE? "))
    print(" ")
    price = float(input("WHAT IS THE PRICE? "))
    print(" ")
    print("THANK YOU FOR BUYING "+name+".")
    print(" ")
    total = total+price
print("====================================================")
print(" ")
print("YOUR PURCHASE HAS COME OUT AS "+str(total))
print(" ")
print("THANK YOU FOR SHOPPING AT NAT HWAG UNOFFICIAL GROCERY STORE FOR STEALING MONEY")
print(" ")
print("====================================================")