print("||| NAT HWAG UNOFFICIAL BOX GENERATOR FOR PEOPLE WHO CAN'T DRAW |||")
print(" ")
print("============================================")
print(" ")
x = int(input("ENTER A WIDTH OF THE BOX: "))
print(" ")
print("============================================")
print(" ")
y = int(input("ENTER A HEIGHT OF THE BOX: "))
print(" ")
print("============================================")
print(" ")
symbol = input("ENTER A SYMBOL FOR THE BOX: ")
print(" ")
print("============================================")
print(" ")
for m in range (0,y):
    for n in range (0,x):
        print(symbol, end = (" "))
    print("")
print(" ")
print(" ")
print("============================================")