print("NAT HWAG UNOFFICIAL 5 JOKE GENERATOR FOR HUMORLESS PEOPLE!")
print(" ")
print("=======================================================================")
print(" ")
answer = input("Do you want a joke? (y/n): ")
if answer == "y":
    print(" ")
    print("Okay, here we go!")
elif answer == "n":
    print(" ")
    print("Too bad.")
else:
    print(" ")
    print("That wasn't an option but you still get a joke.")
print(" ")
print("=======================================================================")
print(" ")
jokes = ["What’s the best thing about Switzerland? I don't know the flag is a big plus", "I visited my new friend in his apartment. He told me to make myself at home. So I threw him out. I hate having visitors.", "Do you know the phrase “One man’s trash is another man’s treasure”? Wonderful saying, horrible way to find out that you were adopted.", "What’s red and bad for your teeth? A brick.", "They laughed at my crayon drawing. I laughed at their chalk outline."]
print(jokes[0])
print(" ")
print(jokes[1])
print(" ")
print(jokes[2])
print(" ")
print(jokes[3])
print(" ")
print(jokes[4])
print(" ")
print("=======================================================================")